import { z } from "zod";

import { zodGeometryPoint } from "../geometryPoint";

export const zodOrder = z.object({
  id: z.number(),
  originalOrderID: z.number(),
  enterpriseID: z.number(),
  statusID: z.number(),
  trackCode: z.string(),
  paymentMethodID: z.number(),
  serviceID: z.number(),
  packageEnvelope: z.string(),
  packageWeight: z.number(),
  packageSizeID: z.number(),
  productDescription: z.string(),
  productPrice: z.number(),
  reverseLogistic: z.boolean().nullish(),
  crossdocking: z.boolean(),
  pickUpBranchID: z.number().nullish(),
  pickUpAddress: z.string().nullish(),
  pickUpPoint: zodGeometryPoint.nullish(),
  pickUpPostalCode: z.string().nullish(),
  pickUpAddressReference: z.string().nullish(),
  pickUpSecondaryReference: z.string().nullish(),
  pickUpNotes: z.string().nullish(),
  pickUpContactName: z.string().nullish(),
  pickUpContactPhone: z.string().nullish(),
  pickUpContactDocumentTypeID: z.number().nullish(),
  pickUpContactDocumentNumber: z.string().nullish(),
  pickUpContactEmail: z.string().nullish(),
  dropBranchID: z.number().nullish(),
  dropPostalCode: z.string().nullish(),
  dropAddressReference: z.string().nullish(),
  dropPrimaryReference: z.string().nullish(),
  dropSecondaryReference: z.string().nullish(),
  dropNotes: z.string().nullish(),
  dropContactName: z.string().nullish(),
  dropContactPhone: z.string().nullish(),
  dropContactDocumentTypeID: z.number().nullish(),
  dropContactDocumentNumber: z.string().nullish(),
  dropContactEmail: z.string().nullish(),
  cityID: z.number(),
  polygonID: z.number(),
  distance: z.number().nullish(),
  isPickedUp: z.boolean().nullish(),
  createdAt: z.string().datetime({ offset: true }),
  updatedAt: z.string().datetime({ offset: true }),
});

export type orderDTO = z.infer<typeof zodOrder>;
