import { GenericClass } from "../generic.class";
import { geometryPointDTO } from "../geometryPoint";
import { orderDTO } from "./order.dto";

export class Order extends GenericClass<orderDTO> {
  declare id: number;
  declare originalOrderID: number;
  declare enterpriseID: number;
  declare statusID: number;
  declare trackCode: string;
  declare paymentMethodID: number;
  declare serviceID: number;
  declare packageEnvelope: string;
  declare packageWeight: number;
  declare packageSizeID: number;
  declare productDescription: string;
  declare productPrice: number;
  declare reverseLogistic: boolean;
  declare crossdocking: boolean;
  declare pickUpBranchID: number;
  declare pickUpAddress: string;
  declare pickUpPoint: geometryPointDTO;
  declare pickUpPostalCode: string;
  declare pickUpAddressReference: string;
  declare pickUpSecondaryReference: string;
  declare pickUpNotes: string;
  declare pickUpContactName: string;
  declare pickUpContactPhone: string;
  declare pickUpContactDocumentTypeID: number;
  declare pickUpContactDocumentNumber: string;
  declare pickUpContactEmail: string;
  declare dropBranchID: number;
  declare dropPostalCode: string;
  declare dropAddressReference: string;
  declare dropPrimaryReference: string;
  declare dropSecondaryReference: string;
  declare dropNotes: string;
  declare dropContactName: string;
  declare dropContactPhone: string;
  declare dropContactDocumentTypeID: number;
  declare dropContactDocumentNumber: string;
  declare dropContactEmail: string;
  declare cityID: number;
  declare polygonID: number;
  declare distance: number;
  declare isPickedUp: boolean;
  declare createdAt: Date;
  declare updatedAt: Date;
}
